import '../styles/globals.css'
import { Roboto } from 'next/font/google'

// internal components
import HeaderStandard from '@/components/Headers/HeaderStandard/HeaderStandard'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <HeaderStandard />
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
